export const actionType = {
  ADD_FAV: "ADD_FAV",
  DELETE_FAV: "DELETE_FAV",
  UPDATE_FAV_STATUS: "UPDATE_FAV_STATUS",
  ADD_TO_CART: "ADD_TO_CART",
  DEC_CART_ITEM: "DEC_CART_ITEM",
  INC_CART_ITEM: "INC_CART_ITEM",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
  SHOW_TOTAL: "SHOW_TOTAL",
};
